import project1 from "../assets/projects/project-1.jpg";
import project2 from "../assets/projects/project-2.jpg";
import project3 from "../assets/projects/project-3.jpg";
import project4 from "../assets/projects/project-4.jpg";

export const HERO_CONTENT = `I am a passionate front end developer with a knack for crafting robust and scalable web applications. With total 5+ years of experience in IT, I have honed my skills in front-end technology like React.js as well as other technologies like Javascript, ES6, Tailwind CSS, CSS and HTML. My goal is to leverage my expertise to create innovative solutions that drive business growth and deliver exceptional user experiences.`;

export const ABOUT_TEXT = `As a dedicated professional with 5+ years of experience in the IT industry, I specialize in the design and development of frontend solutions and Single Page Applications using React.js. I bring strong analytical, organizational, and planning skills, alongside a collaborative mindset that enhances team performance. Known for my adaptability and positive approach, I consistently strive to deliver high-quality results aligned with organizational goals.`;

export const EXPERIENCES = [
  {
    year: "Dec 2022 - Present",
    role: "Senior Analyst",
    company: "Accenture",
    description: ` developed and maintained web applications using JavaScript and React.js.Collaborated with backend developers to integrate front-end components with server-side logic.`,
    technologies: ["Javascript", "React", "GraphQL", "CSS", "HTML"],
  },
  {
    year: "Feb 2022 - Nov 2022",
    role: "Software Developer",
    company: "Wipro Technologies",
    description: `Designed and developed user interfaces for web applications using React.js and CSS libraries. Worked closely with backend developers to integrate frontend components with APIs. Implemented UI designs and optimized frontend performance.`,
    technologies: ["React", "CSS", "HTML"],
  },
  {
    year: "May 2020 - Feb 2022",
    role: "Associate Consultant",
    company: "Wipro Technologies",
    description: `Responsibilities includes Implementing, Configuring, Monitoring,
    Tunning and Troubleshooting the SAP technical environment well as
    Scheduling and executing the SAP system.`,
    technologies: ["SAP GUI", "PUTTY"],
  },
  {
    year: "Sept 2019 - Apr 2020",
    role: "Project Engineer",
    company: "Wipro Technologies",
    description: `Contributed to the development of web applications using JavaScript and React.js. Built reusable components and front-end libraries for future use. Learnt and understood user interaction`,
    technologies: ["React", "Javascript", "CSS", "HTML"],
  },
];

export const PROJECTS = [
  {
    title: "Portfolio Website",
    image: project3,
    description:
      "A personal portfolio website showcasing projects, skills, and contact information.",
    technologies: ["HTML", "CSS", "React", "Framer Motion", "Tailwind CSS"],
    URL: "https://kushalgupta22.netlify.app/",
  },
  {
    title: "RoboFriends Application",
    image: project1,
    description:
      "This is a React Application called Robofriends where a user can search his friends in the search bar and the name will be filtered out dynamically according to the keywords which user will type.",
    technologies: ["HTML", "CSS", "React", "Axios"],
    URL: "https://kushal1922.github.io/Robo-Friends/",
  },
  {
    title: "Accordian Application",
    image: project2,
    description:
      "This is an Accordian Application in which the user will able to see the content when expanding the (+) icon in the screen.",
    technologies: ["HTML", "CSS", "React", "Axios"],
    URL: "https://kushal1922.github.io/Redux-Accordian/",
  },

  {
    title: "Paragraph Generator",
    image: project4,
    description:
      "This is a React Application where user can get one random Paragraph by clicking on a button. The paragraph will be fetched from one JSON file. Different paragraphs will be generated by changing the numbers from the input field.",
    technologies: ["HTML", "CSS", "React", "Axios"],
    URL: "https://kushal1922.github.io/Para-Fetch/",
  },
];

export const CONTACT = {
  address: "VTP Leonara, Pune , Mahalunge, 411045",
  phoneNo: "+91-9973041106",
  email: "kushal11050@gmail.com",
};
